### ISSUE TITLE
How to define CHARSET when connecting to Teradata?

### ISSUE THREAD

**Issue by YangAi** [Teradata/nodejs-driver#38]
Hello,

I'm wondering how can I add parameters when connecting to Teradata like I did when using JDBC?

For example,

jdbc:teradata://HOST/CHARSET=ASCII,TMODE=TERA,CLIENT_CHARSET=EUC_CN

Thank you so much!

**Comment by adamtwo** [comment]
@YangAi ,
currently, there is not a way to specify a character set in the nodejs-driver. As far as I can tell, this is a limitation of the underlying `@teradataprebuilt/nativelib` library. I'll check with the team if there are any workarounds.

thanks,
Adam

**Comment by adamtwo** [comment]
@YangAi ,
sorry it took so long to get back to you. 

* When it comes to `CLIENT_CHARSET`, it's been deprecated even in JDBC. It was useful to help handle non-ASCII chars in ASCII tables. The recommended practice is to store data in Teradata using the correct encoding. 
* As to `CHARSET` parameter, this is a gap in the driver. The driver supports only `UTF-8` encoding. 

Now, specifically about your situation, since your jdbc URL uses `CLIENT_CHARSET=EUC_CN` I'm assuming the character set in the database is `SCHGB2312_1T0`. If you read the data using the nodejs driver, it will assume UTF-8. To convert to EUC_CN, you will first need to convert the UTF-8 representation to bytes and then read bytes as `EUC_CN`. I've not tried it myself, but something like this should work:

```
Buffer.from(stringRetrivedFromTeradata, 'utf8').toString('euc_cn');
```

Let me know if this doesn't resolve your issue.

**Comment by YangAi** [comment]
> @YangAi , sorry it took so long to get back to you.
> 
> * When it comes to `CLIENT_CHARSET`, it's been deprecated even in JDBC. It was useful to help handle non-ASCII chars in ASCII tables. The recommended practice is to store data in Teradata using the correct encoding.
> * As to `CHARSET` parameter, this is a gap in the driver. The driver supports only `UTF-8` encoding.
> 
> Now, specifically about your situation, since your jdbc URL uses `CLIENT_CHARSET=EUC_CN` I'm assuming the character set in the database is `SCHGB2312_1T0`. If you read the data using the nodejs driver, it will assume UTF-8. To convert to EUC_CN, you will first need to convert the UTF-8 representation to bytes and then read bytes as `EUC_CN`. I've not tried it myself, but something like this should work:
> 
> ```
> Buffer.from(stringRetrivedFromTeradata, 'utf8').toString('euc_cn');
> ```
> 
> Let me know if this doesn't resolve your issue.

Thanks! It helps a lot. I resolved the issue with iconv.
