### ISSUE TITLE
Query is failing with higher records

### ISSUE THREAD

**Issue by kamalsaha** [Teradata/nodejs-driver#45]
Hi Team,

When I am trying to run a query with more then 500 records its filing with time our error.
if the row count is less then 500 its running fine.

Please suggest to fix the issue.

**Comment by adamtwo** [comment]
@kamalsaha , there is no cap at 500 items in the driver. You must be hitting a limit defined somewhere else in the infrastructure. As with any timeout, you have two options:
1. Optimize your operation so that it doesn't hit the timeout.
2. Increase the timeout.

Could you please paste the timeout error message so that we can figure out where it's coming from?

**Comment by adamtwo** [comment]
No response for 30 days, closing the issue.
