### ISSUE TITLE
npm install teradata-nodejs-driver is not woring

### ISSUE THREAD

**Issue by kpr9991** [Teradata/nodejs-driver#51]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/46647933/155837794-b279d2e2-9aac-409f-ae30-657e1ef317af.png">
I have Nodejs version 17.x and npm version 8.x

**Comment by adamtwo** [comment]
@kpr9991 , this is an issue with `ffi-napi` that `teradata-nodejs-driver` depends on. `ffi-napi` contains native code that needs to be compiled during the installation process. It looks like you are running on Windows. You need to have Visual Studio 2017 in order to complete the compilation. There are many moving parts in the toolchain and it's very common to run into issues. See this guide for help: https://spin.atomicobject.com/2019/03/27/node-gyp-windows/ .
